### ISSUE TITLE
Feature normalization

### ISSUE THREAD

**Issue by Nadian-Ali** [LeeDoYup/bottom-up-attention-tf#3]
could you help on this matter?
Did you do any normalization on the visual features?

**Comment by LeeDoYup** [comment]
https://github.com/LeeDoYup/bottom-up-attention-tf/blob/0500c0717e9b9f65c8406bd3c2b30c8b83b36ebb/models/ops.py#L142

The classifier of multi-modal features has normalization layer.
Sorry for late relpy.
