### ISSUE TITLE
where do the weights of the attention model update? 

### ISSUE THREAD

**Issue by Nadian-Ali** [LeeDoYup/bottom-up-attention-tf#4]
Hi 
in the attention model where the weights w are applied to the input vector w* concat[imFeatures,QuestionEmbddding] 
I can't figure out where the values of w come from or how they are updated?!!! can you help with this problem?

**Comment by LeeDoYup** [comment]
https://github.com/LeeDoYup/bottom-up-attention-tf/blob/0500c0717e9b9f65c8406bd3c2b30c8b83b36ebb/models/top_down_attention.py#L48

Attention score has trainable parameter . thank you
